# fly.toml app configuration file generated for lector-manifiestos on 2025-01-27T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lector-manifiestos"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  STORAGE_TYPE = "local"
  BASE_FOLDER = "MANIFIESTOS"
  EXCEL_FOLDER = "EXCEL"
  DATA_FOLDER = "data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory_mb = 512
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "data_volume"
  destination = "/data"

